export const ADD_TO_CART = "ADD_TO_CART";
export const DECREASE_ITEM_QUANTITY = "DECREASE_ITEM_QUANTITY";
export const INCREASE_ITEM_QUANTITY = "INCREASE_ITEM_QUANTITY";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const GET_CART_TOTAL_PRICE = "GET_CART_TOTAL_PRICE";
export const CLEAR_CART = "CLEAR_CART"